#this program is all about Shanvi's daily routin
print("1.shanvi's Daily Routine")
print("2.wake up at 6:30am")
print("3.get ready for school")
print("4.eat breakfast")
print("5.get in the school bus")
print("6.play with my friends")
print("7.at 8:25 i go to class")
print("8.then recess")
print("9.at 12pm i eat lunch")
print("10.I play basketball with my friends")
print("after that i go back to class")
print("i get back in the bus")
print("reach home")
print("eat a snack")
print("take a shower")
print("eat dinner")
print("then i do my homework")
print("play games on my ipad")
print("finally i sleep at 9:30pm")